Create manifest.devkit.json
juniper-garden/twig_esp32_mod pull request #3
Opened 2022-08-15 23:27 UTC by ameyer-eng

Created a manifest.devkit.json again for the dev board.

It builds and loads.

Issue1:  "No Wii-fi SSID"  from XsBug
Issue2:  "/moddable/modules/pins/I2C/i2c.c write failed

2022-08-18 02:55 UTC, ameyer-eng commented
# Changes:

## Added a manifest file for the Esp32c3 dev kit.  

At this point it is just a copy of manifest.json with minor changes.

## Commented out wifi connection in run() in twig class

There was nothing wrong with the original code.  I wanted to see the Bluetooth connection and by design it kept connecting to my wifi network. 

## Added try-catch statement for BME280 sensor. 

If the initialization of the sensor fails, it will not run the rest of the sensor setup code and will use a trace function to 
alert the user that the sensor is not connected

2022-08-21 16:06 UTC, dashcraft requested changes
Let's make sure to remove the console logs blocking the connection to the network

2022-08-21 16:06 UTC, dashcraft commented on twig_bme280_esp32_c3/main.js
> +        //commented out below to force BLE server to start...
We shouldn't commit this to the repository

2022-08-22 23:58 UTC, ameyer-eng commented on twig_bme280_esp32_c3/main.js
> +        //commented out below to force BLE server to start...
I want to ensure I understand correctly. Do you mean the comments I made so it would start the BLE server? I'm not sure what the console logs are?

2022-08-23 00:34 UTC, ameyer-eng commented on twig_bme280_esp32_c3/main.js
> +        //commented out below to force BLE server to start...
I just created a commit that removed the comments blocking the wifi connection.  Let me know if this is correct.

2022-08-23 15:46 UTC, dashcraft commented on twig_bme280_esp32_c3/main.js
> +        //commented out below to force BLE server to start...
Yup thats fine!

2022-08-23 15:46 UTC, dashcraft approved these changes

2022-08-25 15:54 UTC, merged